import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import SmoothScroll from "@/components/SmoothScroll";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased darkMode">
        <SmoothScroll>
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
